#!/usr/bin/env python3                                                                        
##                                                                                            
## EPITECH PROJECT, 2018                                                                      
## 106bombyx                                                                           
## File description:                                                                          
## math                                                                                       
##

import sys
import math

def calc(x, k):
    x = (k * x) *((1000 - x) / 1000)
    return (x)

def form_one():
    x = float(sys.argv[1])
    k = float(sys.argv[2])
    i = 1
    while i <= 100:
        print("{} {:.2f}".format(i, x))
        x = calc(x, k)
        i += 1

def form_two():
    k = 1.00
    i = 1
    i1 = float(sys.argv[2])
    i2 = float(sys.argv[3])

    while k <= 4.00:
        i = 1
        x = float(sys.argv[1])
        while i <= i2:
            if i >= i1:
                print("{:.2f} {:.2f}".format(k, x))
            x = calc(x, k)
            i += 1
        k += 0.01

def main():
    if len(sys.argv) == 3 :
        form_one()
    elif len(sys.argv) == 4:
        form_two()

if __name__ == "__main__":
    main()
