#!/usr/bin/env python3                                                                        
##                                                                                            
## EPITECH PROJECT, 2018                                                                      
## 106bombyx                                                                           
## File description:                                                                          
## math                                                                                       
##

import sys
import math

def check_for_err():
    halp = open("help", "r")

    if len(sys.argv) > 1 and sys.argv[1] == "-h":
        print(halp.read())
        sys.exit(0)
    elif len(sys.argv) < 3:
        print("Too few arguments. Try -h for more informations.")
        sys.exit(84)
    elif len(sys.argv) > 4:
        print("Too much arguments. Try -h for more informations.")
        sys.exit(84)

    i = 1
    if len(sys.argv) == 4:
        while i < 4:
            try:
                flag = int(sys.argv[i])
            except ValueError:
                print("Flag error. Try -h for more informations.")
                sys.exit(84)
            if flag < 0:
                print("Flag error. Try -h for more informations.")
                sys.exit(84)
            i += 1
        if sys.argv[2] > sys.argv[3]
    if len(sys.argv) ==	3:
        try:
            flag = int(sys.argv[1])
        except ValueError:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
        if flag < 0:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
        try:
            flag = float(sys.argv[2])
        except ValueError:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
        if flag > 4 or flag < 1:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)


def calc(x, k):
    x = (k * x) *((1000 - x) / 1000)
    return (x)

def form_one():
    x = float(sys.argv[1])
    k = float(sys.argv[2])
    i = 1
    while i <= 100:
        print("{} {:.2f}".format(i, x))
        x = calc(x, k)
        i += 1

def form_two():
    k = 1.00
    i = 1
    i1 = float(sys.argv[2])
    i2 = float(sys.argv[3])

    while k <= 4.00:
        i = 1
        x = float(sys.argv[1])
        while i <= i2:
            if i >= i1:
                print("{:.2f} {:.2f}".format(k, x))
            x = calc(x, k)
            i += 1
        k += 0.01

def main():
    check_for_err()
    if len(sys.argv) == 3 :
        form_one()
    elif len(sys.argv) == 4:
        form_two()

if __name__ == "__main__":
    main()
